#!/usr/bin/env bash
# Bash script groups visitors by IP and HTTP status code, and displays the data
awk 'NF >= 9 && $9 ~ /^[0-9]{3}$/ {counts[$1" "$9]++} 
     END {for (key in counts) print counts[key], key}' apache-access.log | sort -nr
