#!/usr/bin/env bash
# Bash script groups visitors by IP and HTTP status code, and displays the data
awk '{counts[$1" "$9]++} END {for (key in counts) print counts[key], key}' apache-access.log | sort -nr
