#!/usr/bin/env bash
# Bash script groups visitors by IP and HTTP status code, and displays the data
awk 'NF>=9 && $1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && $9 ~ /^[0-9]{3}$/ { print $1, $9 }' apache-access.log \
  | sort | uniq -c | sort -nr
