#!/usr/bin/env bash
# Display time from hour 0 to 12 and minutes 1 to 59 using while loops
minutes=1
hours=0
while [ $hours -lt 13 ]; do
    echo Hour: $hours
    while [ $minutes -lt 60 ]; do
	echo $minutes
	(( minutes+=1 ))
    done
    (( minutes=1 ))
    (( hours+=1 ))
done
