#!/usr/bin/env bash
# Display time from hour 0 to 12 and minutes 1 to 59 using while loops
hour=0
while [ $hour -le 12 ]; do
  minute=1
  while [ $minute -le 59 ]; do
    printf "%02d:%02d\n" $hour $minute
    ((minute++))
  done
  ((hour++))
done
