#!/usr/bin/env bash
# Displays to infinity and beyond indefinitely With a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
counter=2
while [ $counter -gt 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
